### ISSUE TITLE
unsupport signal SIGPIPE (ruby on window x64).

### ISSUE THREAD

**Issue by staticdnweb** [specious/facebook-cli#14]
i face this error: unsupport signal SIGPIPE
OS: Window 10
 please help

**Comment by specious** [comment]
Thank you for reporting this bug.  I didn't realize Windows might not have a PIPE signal, or think to check if a signal is present in the host environment before invoking [Signal.trap](http://ruby-doc.org/core-2.4.1/Signal.html#method-c-trap).

Looking into the issue, I discovered that this has been tackled by multiple projects and chose the same approach as https://github.com/jneen/rouge/commit/c46f01b

Should be fixed in facebook-cli 1.5.4.
