### ISSUE TITLE
Cannot run the app

### ISSUE THREAD

**Issue by ihsankl** [specious/facebook-cli#36]
when i tried to run the app, it crashed like the following pic. im using manjaro

![image](https://user-images.githubusercontent.com/55323174/164017502-fd6180d8-8304-4efa-8700-3695be2e54ea.png)

**Comment by specious** [comment]
Thank you for reporting this.

I'd like to say that this project has been sitting for a while and I'd be surprised if it's possible to even get it to work at this point.

However, I'm getting the same error after doing `gem install facebook-cli`. I updated the dependencies and explicitly listed [webrick](https://github.com/ruby/webrick) as a dependency and now it works:

https://github.com/specious/facebook-cli/blob/93e1bec8fd8e56cba854b5b9099ff5fa1caefaf1/facebook-cli.gemspec#L19-L23

The fix is in 93e1bec8fd8e56cba854b5b9099ff5fa1caefaf1 which is also now published as gem version 1.7.2.
